sudo: required
services:
  - docker

before_install:
  #- docker build -t ballayo/docker-react .
  #- docker build -t  ballayo/docker-react -f Dockerfile .
  - docker build -t  ballayo/docker-react -f Dockerfile.dev .

script:
  #- docker run -e CI=true ballayo/docker-react npm run test
  - docker run ballayo/docker-react npm run test -- -- coverage  

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-131145187893"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY